theme: jekyll-theme-cayman
title: Jonathan Leung
description: 

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      css: "/assets/css/custom.css"
