theme: jekyll-theme-cayman
title: Jonathan Leung
description: Aspiring Geomatics Co-op Student

plugins:
  - jekyll-remote-theme

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      css: "/assets/css/custom.css"
